insert into public.sports (nom, categorie, actif) values
-- Sports collectifs
('Basketball 3x3 Hommes', 'Collectif', true),
('Basketball 3x3 Femmes', 'Collectif', true),
('Handball Hommes', 'Collectif', true),
('Handball Femmes', 'Collectif', true),
('Volleyball Hommes', 'Collectif', true),
('Football Hommes', 'Collectif', true),
-- Sports individuels
('Tennis de table', 'Individuel', true),
('Padel', 'Individuel', true),
('Boxe', 'Individuel', true),
('Triathlon', 'Individuel', true),
('Tennis', 'Individuel', true),
('Gymnastique Artistique', 'Individuel', true),
('Gymnastique Rythmique', 'Individuel', true),
('Tir à l''arc', 'Individuel', true),
('Voile', 'Individuel', true),
('Athlétisme', 'Individuel', true),
('Natation', 'Individuel', true),
('Cyclisme', 'Individuel', true),
('Tir Sportif', 'Individuel', true),
('Haltérophilie', 'Individuel', true),
('Lutte', 'Individuel', true),
('Aviron', 'Individuel', true),
('Équitation', 'Individuel', true),
('Canoë Sprint', 'Individuel', true),
('Judo', 'Individuel', true),
('Escrime', 'Individuel', true),
('Karaté', 'Individuel', true),
('Pétanque', 'Individuel', true),
('Taekwondo', 'Individuel', true);